# Generated by Django 3.1.4 on 2020-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
