# Generated by Django 3.1.4 on 2020-12-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0006_product_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type',
            field=models.CharField(choices=[('gas', 'Бензиновый'), ('electric', 'Электрический'), ('diesel', 'Дизельный')], default='gas', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(choices=[('canada', 'Канада'), ('usa', 'Америка'), ('russia', 'Россия'), ('china', 'Китай')], default='russia', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='test_model_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_issue',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='onlinestore.brand'),
        ),
    ]
