# Generated by Django 3.1.4 on 2020-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0007_auto_20201216_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
