# Generated by Django 3.1.4 on 2020-12-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0008_product_number_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images/categories/'),
        ),
    ]
