# Generated by Django 3.1.4 on 2021-01-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0010_auto_20210129_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
        migrations.AddField(
            model_name='product',
            name='bought_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='onlinestore.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='engine_power',
            field=models.IntegerField(verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='engine_type',
            field=models.CharField(choices=[('gas', 'Бензиновый'), ('electric', 'Электрический'), ('diesel', 'Дизельный')], max_length=10, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='manufacturer_country',
            field=models.CharField(choices=[('canada', 'Канада'), ('usa', 'Америка'), ('russia', 'Россия'), ('china', 'Китай')], max_length=10, verbose_name='Страна-производитель'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='model_name',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='number_of_seats',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='year_of_issue',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
